# Generated by Django 4.0.3 on 2022-05-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0003_alter_place_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField(null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[('0', 'etc'), ('1', 'Classroom'), ('2', 'Restaurant')], default='0')),
                ('floor', models.PositiveSmallIntegerField(null=True)),
                ('information', models.CharField(max_length=500, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='place.place')),
                ('tags', models.ManyToManyField(related_name='tag_rooms', to='place.tag')),
            ],
        ),
    ]
