version: '3'

volumes:
  snumap_db_dev: {}
  snumap_packages: {}

services:
  db:
    image: mysql:8.0.27
    restart: always
    command: --lower_case_table_names=1
    environment:
        - MYSQL_DATABASE=snumapdb
        - MYSQL_USER=snumapdbuser
        - MYSQL_PASSWORD=secret1234  
        - MYSQL_ROOT_PASSWORD=secret1234  
        - TZ=Asia/Seoul
    command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    volumes:
        - ./db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=snumapdb
      - DJANGO_DB_USERNAME=snumapdbuser
      - DJANGO_DB_PASSWORD=secret1234
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    command: /start-dev.sh
    volumes:
      - ./snumap:/app
      - snumap_packages:/usr/local/lib/python3.9/site-packages/
    tty: true

#http://raccoonyy.github.io/docker-usages-for-dev-environment-setup/