version: '3'

volumes:
  snumap_db_dev: {}
  snumap_packages: {}

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - snumap_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=snumapdb
      - POSTGRES_USER=snumapdbuser
      - POSTGRES_PASSWORD=secret1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=snumapdb
      - DJANGO_DB_USERNAME=snumapdbuser
      - DJANGO_DB_PASSWORD=secret1234
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    command: /start-dev.sh
    volumes:
#      - ./requirements.txt:/app/requirements.txt
      - ./snumap:/app
      - snumap_packages:/usr/local/lib/python3.9/site-packages/
    tty: true

#http://raccoonyy.github.io/docker-usages-for-dev-environment-setup/