FROM python:3.9.11
MAINTAINER esc5221 <esc5221@gmail.com>

RUN \
    apt-get update -y&&\
    apt-get install gunicorn -y

ENV PYTHONUNBUFFERED=0
ENV PYTHONUSERBASE=/usr/local/
ENV PATH=${PYTHONUSERBASE}lib/python3.9/site-packages/bin:${PATH}

WORKDIR /app

ADD compose/django/start-prod.sh /start-prod.sh

RUN chmod +x /*.sh